export type Recipe = {
  id: string;
  title: string;
  category: string;
  description: string;
  duration: string;
  servings: string;
  emoji: string;
  ingredients: string;
  steps: string;
  featured?: boolean;
};

/** Recettes importées du Livre de recettes Notion de Nico le 13 septembre 2026. */
export const notionRecipes: Recipe[] = [
  { id: "notion-cocktail-halloween", title: "Cocktail Halloween", category: "Boisson", emoji: "🍹", duration: "25 min", servings: "À préciser", description: "Un cocktail chaud à la pomme, à la citrouille et aux épices, relevé de rhum brun.", ingredients: "1 litre de jus de pomme\n500 ml de purée de citrouille\n1/2 cuillère à café de cannelle\n1/2 cuillère à café de gingembre\n1/2 cuillère à café de muscade\n13 cl de rhum brun épicé\n13 cl de crème liquide", steps: "Mélanger le jus de pomme, la purée de citrouille et les épices à feu vif.\nPorter à ébullition, puis réduire à feu moyen.\nLaisser mijoter 10 minutes en remuant de temps en temps.\nFiltrer et jeter la purée.\nIncorporer le rhum dans la boisson chaude." },
  { id: "notion-marbre-savane", title: "Marbré façon Savane", category: "Pâtisserie", emoji: "🍫", duration: "55 min", servings: "À préciser", description: "Un cake marbré vanille et chocolat, léger et généreux.", ingredients: "3 œufs\n70 g de sucre\n70 g de beurre fondu\n1 sachet de levure chimique\n250 g de farine\n150 g de lait\n150 g de chocolat noir fondu\n1 c. à café d’arôme ou de poudre de vanille", steps: "Préchauffer le four à 165 °C.\nFouetter les œufs et le sucre 10 minutes, jusqu’à ce que le mélange double de volume.\nAjouter le beurre fondu, la levure et la farine, puis le lait.\nRépartir la préparation dans deux bols : ajouter la vanille dans l’un, le chocolat fondu dans l’autre.\nDans un moule à cake beurré, alterner la moitié de pâte vanille et la moitié de pâte chocolat, puis recommencer.\nEnfourner 45 minutes. Vérifier avec la lame d’un couteau et laisser tiédir avant de démouler." },
  { id: "notion-gateau-banane", title: "Gâteau moelleux à la banane", category: "Pâtisserie", emoji: "🍌", duration: "55 min", servings: "À préciser", description: "Un gâteau ultra moelleux, au bon goût de banane, parfait pour le goûter ou le petit-déjeuner.", ingredients: "170 g de farine\n110 g de sucre semoule\n60 g de beurre mou\n2 bananes bien mûres\n2 œufs\n1 c. à soupe de lait\n1 c. à soupe de levure chimique\n1 pincée de sel", steps: "Préchauffer le four à 180 °C.\nFouetter les œufs et le sucre jusqu’à ce que le mélange blanchisse.\nAjouter le beurre mou, la farine, la levure, le lait et le sel.\nÉcraser les bananes à la fourchette et les ajouter à la pâte.\nVerser dans un moule à cake beurré et fariné.\nCuire environ 45 minutes, vérifier avec la pointe d’un couteau et laisser refroidir avant de démouler." },
  { id: "notion-muffin-potimaron", title: "Muffin potimaron", category: "Pâtisserie", emoji: "🥄", duration: "45 min", servings: "À préciser", description: "Des muffins au potimarron parfumés à la cannelle.", ingredients: "1 potimarron\n300 g de farine\n250 ml de lait\n100 g de sucre en poudre\n80 g de beurre\n2 œufs\n1 c. à café de cannelle\n1 sachet de levure chimique", steps: "Peler, épépiner et cuire le potimarron 15 minutes à la cocotte. Mixer sa chair et conserver 300 g de purée. Préchauffer le four à 180 °C.\nFaire fondre le beurre. Fouetter les œufs et le sucre, puis ajouter le beurre fondu et le lait froid.\nMélanger farine, levure et cannelle, puis les incorporer. Ajouter la purée de potimarron.\nBeurrer des moules à muffins, les remplir aux 3/4 et cuire environ 30 minutes. Laisser tiédir avant de démouler." },
  { id: "notion-marbre-zebre", title: "Marbré zébré", category: "Pâtisserie", emoji: "🥄", duration: "50 min", servings: "À préciser", description: "Un marbré à l’effet zébré, alternant pâte vanille et cacao.", ingredients: "4 œufs\n200 g de sucre\n20 cl d’huile\n10 cl de lait\n300 g de farine\n2 c. à café de levure (1 sachet)\n20 g de cacao en poudre\n1 c. à café d’extrait de vanille\n1 pincée de sel", steps: "Préchauffer le four à 180 °C.\nMélanger les œufs, le sucre, le sel, l’huile et le lait, puis diviser la pâte en deux.\nDans la première moitié, ajouter 175 g de farine, une cuillère à café de levure et la vanille.\nDans la seconde, ajouter 125 g de farine, une cuillère à café de levure et le cacao.\nDans un moule beurré, déposer au centre 3 cuillères à soupe de pâte cacao puis 3 de pâte vanille. Répéter en alternant.\nCuire 40 minutes à 180 °C." },
  { id: "notion-cake-citron-pavot", title: "Cake citron pavot", category: "Pâtisserie", emoji: "🍋", duration: "50 min", servings: "À préciser", description: "Un cake citronné aux graines de pavot, frais et moelleux.", ingredients: "100 g de beurre à température ambiante\n150 g de sucre\n2 œufs\nLe zeste et le jus d’un gros citron\n200 g de farine\n1 sachet de levure chimique\n1 c. à café de bicarbonate de soude (facultatif)\n2 pincées de sel\n5 cl de lait\n2 c. à soupe de graines de pavot", steps: "Battre vivement le beurre et le sucre jusqu’à obtenir un mélange crémeux.\nAjouter les autres ingrédients dans l’ordre, en mélangeant entre chaque ajout.\nVerser dans un moule à cake beurré.\nCuire 40 à 45 minutes dans un four préchauffé à 180 °C, jusqu’à ce qu’une lame ressorte propre. Laisser tiédir 10 minutes avant de démouler." },
  { id: "notion-moelleux-chocolat", title: "Moelleux chocolat", category: "Pâtisserie", emoji: "🍫", duration: "50 min", servings: "À préciser", description: "Un gâteau au chocolat moelleux, à finir d’un voile de sucre glace.", ingredients: "180 g de chocolat noir\n180 g de beurre\n120 à 180 g de sucre (selon le goût)\n100 g de farine\n1/2 sachet de levure\n6 œufs\nSucre glace pour la décoration (facultatif)", steps: "Préchauffer le four à 180 °C.\nFaire fondre le beurre avec le chocolat au bain-marie ou à feu doux.\nSéparer les blancs des jaunes. Fouetter les jaunes avec le sucre, puis incorporer farine et levure. Ajouter le mélange chocolat-beurre.\nMonter les blancs en neige et les incorporer délicatement.\nVerser dans un moule rond de 20 à 24 cm. Cuire 35 à 40 minutes, en couvrant de papier cuisson à mi-cuisson si besoin. Laisser refroidir, démouler et décorer de sucre glace." },
  { id: "notion-super-cookies", title: "Super Cookies", category: "Pâtisserie", emoji: "🍪", duration: "25 min", servings: "À préciser", featured: true, description: "Des cookies aux pépites de chocolat, simples à préparer et toujours réconfortants.", ingredients: "150 g de farine\n75 g de sucre roux (essayer 50 g)\n1/2 sachet de levure chimique\n50 g de beurre fondu\n1 œuf\n1 sachet de sucre vanillé\n100 g de pépites de chocolat", steps: "Préchauffer le four à 180 °C. Mélanger la farine, les sucres, l’œuf et le beurre fondu jusqu’à obtenir une pâte homogène.\nIncorporer la levure et les pépites de chocolat.\nFormer un boudin, découper des morceaux d’environ 2 cm et les aplatir.\nLes disposer sur une plaque et cuire environ 10 minutes. Laisser refroidir après cuisson." },
  { id: "notion-pate-flamekueche", title: "Pâte à flammekueche", category: "Pâte", emoji: "🥄", duration: "À préciser", servings: "À préciser", description: "La pâte maison, toute simple, pour une flammekueche.", ingredients: "250 g de farine\nUn peu de sel\n100 ml d’eau tiède\n50 ml d’huile", steps: "Les instructions de préparation ne sont pas renseignées dans la fiche Notion." },
];
