// Rewrites lib/recipe-photos.ts from the files in public/photos.
// Run "npm run photos" after adding or removing a photo.
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const ids = fs.readdirSync(path.join(root, 'public/photos')).filter(file => file.endsWith('.jpg')).map(file => file.slice(0, -4)).sort();
fs.writeFileSync(path.join(root, 'lib/recipe-photos.ts'), `// Generated by tools/list-photos.cjs from public/photos — do not edit by hand.
const photoIds = new Set<string>(${JSON.stringify(ids, null, 2)});

/** Path of the recipe's photo (public/photos/<id>.jpg, 900 × 600), or null when it has none yet. */
export function recipePhoto(id: string | number) {
  return photoIds.has(String(id)) ? \`/photos/\${id}.jpg\` : null;
}
`);
console.log(ids.length + ' photos listées dans lib/recipe-photos.ts');
