// Prepares the recipe photos found in public/photos:
// - writes a 480 px wide copy of each one in public/photos/sm, for phones;
// - rewrites lib/recipe-photos.ts, the list of recipes that have a photo.
// Run "npm run photos" after adding, replacing or removing a photo.
const fs = require('node:fs');
const path = require('node:path');
const sharp = require('sharp');
const root = path.join(__dirname, '..');
const photos = path.join(root, 'public/photos');
const small = path.join(photos, 'sm');
const ids = fs.readdirSync(photos).filter(file => file.endsWith('.jpg')).map(file => file.slice(0, -4)).sort();

(async () => {
  fs.mkdirSync(small, { recursive: true });
  let made = 0;
  for (const id of ids) {
    const source = path.join(photos, id + '.jpg');
    const target = path.join(small, id + '.jpg');
    // Redone when the full-size photo is newer, so that a replaced photo gets a new small copy.
    if (fs.existsSync(target) && fs.statSync(target).mtimeMs >= fs.statSync(source).mtimeMs) continue;
    await sharp(source).resize({ width: 480 }).jpeg({ quality: 72, mozjpeg: true }).toFile(target);
    made += 1;
  }
  for (const file of fs.readdirSync(small)) if (!ids.includes(file.slice(0, -4))) fs.unlinkSync(path.join(small, file));

  fs.writeFileSync(path.join(root, 'lib/recipe-photos.ts'), `// Generated by tools/list-photos.cjs from public/photos — do not edit by hand.
const photoIds = new Set<string>(${JSON.stringify(ids, null, 2)});

/** Path of the recipe's photo (public/photos/<id>.jpg, 900 × 600), or null when it has none yet. */
export function recipePhoto(id: string | number) {
  return photoIds.has(String(id)) ? \`/photos/\${id}.jpg\` : null;
}

/** The same photo 480 px wide, for small screens. */
export function recipePhotoSmall(id: string | number) {
  return photoIds.has(String(id)) ? \`/photos/sm/\${id}.jpg\` : null;
}
`);
  console.log(ids.length + ' photos listées dans lib/recipe-photos.ts, ' + made + ' petite(s) copie(s) créée(s)');
})();
